#####################################################################################################################
#                                     Zombie Ablockalypse - Configuration file                                      #
#                                            Authors: Jnorr44, iKeirNez                                             #
#####################################################################################################################

##################################################### DIFFICULTY #####################################################

startPoints: 200
# The amount of points all players should start with.

pointIncrease: 100
# How many points are gained per kill.

packapunchLevel: 5
# The minimum level before players can use the pack-a-punch.

perkDuration: max
# The duration in ticks of perks before they are removed automatically.
# NOTE: "max" sets the value to the highest possible integer. Anything too high will break the plugin.

healLevel: 0
speedLevel: 0
damageLevel: 0
regenLevel: 0
juggernautLevel: 0
# Sets the levels at which the corresponding perks can be bought.

healPoints: 500
speedPoints: 1500
damagePoints: 2000
regenPoints: 3000
juggernautPoints: 4000
# Sets the points required to buy the corresponding perks.

enchDamageCost: 400
enchRandomCost: 300
# The amount of points it costs to get an enchantment on your weapon.

mysteryChestCost: 1500
# The amount it costs to buy a mystery item from the mystery box.
# This should be lower than the diamond sword cost from below.

doubleSpeedLevel: 10
# The level at which zombies should double their speed.

wolfLevels:
    - 5 
    - 11
    - 15
    - 18
# The levels to spawn wolves on.

startingItems:
  inventory:
    - 276:5 1
    - 261 2
  armor:
    helmet: 302 5
    chestplate: 311 1
    leggings: 316 6
    boots: 301:5 1
# These items will be given to players when they enter a ZA game
# The format for items are - <item-id>:[damage-value] [amount] [enchantment-name/id] [enchantment level]
# SORRY, THIS IS NOT CURRENTLY WORKING. THIS WILL BE FIXED SOON!

teleportTime: 5
# The amount of time to count down before teleporting.

################################################### MISCELLANEOUS ###################################################

maxPlayers: 4
# The amount of players that you can have at max in your games.

losePerksOnLastStand: true
# Makes players lose all perks when they go into last stand.

pointsGivenOnHelp: 200
# Amount of points to give the player for saving another player.

pointsGivenOnAtomBomb: 600
# Amount of points to give all players when an atom bomb is found.

defaultFriendlyFireMode: false
# The default setting for all games concerning friendly fire.

lastStandThreshold: 10
# The amount of health left before a player is put in last stand.
# Max health is 20, so 10 health = 5 hearts.

powerupChance: 5
# The chances for the 3 powerups. (atom bomb, barrier fix, weapon fix)

blinkers: true
# Makes areas and barriers blink to reveal position and correctness of placement.

addedEffects: true
# Adds extra visual effects to Ablockalypse.

barrierPerFixIncrease: 20
# The amount of points gained per fix of the barrier.

barrierCompleteFixIncrease: 100
# The amount of points gained when the barrier is completely fixed.

movingChests: true
# Moves the active chest around, instead of all chests being active at once.

chestBeacons: true
# Adds beacons above chests to let players see where the active chest is.

clearNearbyMobs: false
# If enabled, clears all mobs near the player so they don't interfere.

###################################################### WEAPONS ######################################################

woodSword: 200
woodSwordLevel: 0

stoneSword: 600
stoneSwordLevel: 0

ironSword: 1200
ironSwordLevel: 5

diamondSword: 2000
diamondSwordLevel: 15

goldSword: 2500
goldSwordLevel: 20

perGrenade: 200
grenadeLevel: 0

# NOTE - Ender Pearls are grenades, and are changed to explode on impact.

#################################################### PLUGIN INTEGRATION #########################################

# CommandsEX by iKeirNez
# NOTE - If CommandsEX is detected and XMPP is enabled, Zombie Ablockalypse will send
# messages to the XMPP chatroom.

xmppAnnounceGameStart: true
xmppAnnounceGameEnd: true
xmppAnnouncePlayerJoinGame: true
xmppAnnouncePlayerLeaveGame: true
xmppAnnounceLastStand: true

#################################################### MAINTENANCE ####################################################

ENABLE_AUTO_UPDATE: false
# Enables automatic updating for Ablockalypse.

DEBUG: false
# Setting this true will make the console spit out a lot of info at you.
# If there is anything that concerns you, post this as an issue on:
# https://github.com/JamesNorris/Ablockalypse/issues