#####################################################################################################################
#                                     Zombie Ablockalypse - Configuration file                                      #
#                                            Authors: Jnorr44, iKeirNez                                             #
#####################################################################################################################

##################################################### DIFFICULTY #####################################################

startPoints: 200
# The amount of points all players should start with.

pointIncrease: 100
# How many points are gained per kill.

packapunchLevel: 5
# The minimum level before players can use the pack-a-punch.

healLevel: 5
speedLevel: 10
damageLevel: 20
regenLevel: 30
# Sets the levels at which the corresponding perks can be bought.

healPoints: 500
speedPoints: 1500
damagePoints: 2000
regenPoints: 3000
# Sets the points required to buy the corresponding perks.

mysteryChestCost: 1500
# The amount it costs to buy a mystery item from the mystery box.
# This should be lower than the diamond sword cost from below.

doubleSpeedLevel: 10
# The level at which zombies should double their speed.

wolfLevels: {5, 11, 15, 18}

startingItems:
  inventory:
    - 276:5 1
    - 261 2
  armor:
    helmet: 302 5
    chestplate: 311 1
    leggings: 316 6
    boots: 301:5 1
# These items will be given to players when they enter a ZA game
# The format for items are - <item-id>:[damage-value] [amount] [enchantment-name/id] [enchantment level]

################################################### MISCELLANEOUS ###################################################

losePerksOnLastStand: true
# Makes players lose all perks when they go into last stand.

pointsGivenOnHelp: 200
# Amount of points to give the player for saving another player.

lastStandThreshold: 3
# The amount of health left before a player is put in last stand.

###################################################### WEAPONS ######################################################

woodSword: 200
woodSwordLevel: 0

stoneSword: 600
stoneSwordLevel: 0

ironSword: 1200
ironSwordLevel: 5

diamondSword: 2000
diamondSwordLevel: 15

goldSword: 2500
goldSwordLevel: 20

perGrenade: 200
grenadeLevel: 0

# NOTE - Ender Pearls are grenades, and are changed to explode on impact.

#################################################### MAINTENANCE ####################################################

DEBUG: false
# Setting this true will make the console spit out a lot of info at you.
# If there is anything that concerns you, post this as an issue on:
# https://github.com/JamesNorris/Ablockalypse/issues