#####################################################################################################################
#                                     Zombie Ablockalypse - Configuration file                                      #
#                                            Authors: Jnorr44, iKeirNez                                             #
#####################################################################################################################

################################################### MISCELLANEOUS ###################################################

startPoints: 200
# The amount of points all players should start with.

pointIncrease: 100
# The amount of points gained when a player kills a mob.

explosivePointIncrease: 20
# The amount of points gained when a player kills a mob with an explosive.

packapunchCost: 10000
packapunchLevel: 0
# The minimum level and points before players can buy the pack-a-punch.

perkDuration: -1
# The time in seconds that perks should last. 
# If set to -1, the perk will last for the maximum amount of time possible.

staminupLevel: 0
deadshotDaiquiriLevel: 0
juggernogLevel: 0
phdFlopperLevel: 0
# Sets the levels at which the corresponding perks can be bought.

staminupPoints: 2000
deadshotDaiquiriPoints: 2500
juggernogPoints: 4000
phdFlopperPoints: 3000
# Sets the points required to buy the corresponding perks.

mysteryChestCost: 1500
# The amount it costs to buy a mystery item from the mystery box.
# This should be lower than the diamond sword cost from below.


wolfLevels:
     - '[5, 5] 100%'
     - '[11, 11] 100%'
     - '[15, 15] 75%'
     - '[18, 18] 50%'
     - '[21, 100) 10%'
# Used to define wolf levels in the game. The brackets used are for mathematical interval notation.
# Ex: - '[20, 23) 50%'
# A '[' bracket makes the number given included, while a '(' bracket does not include the number shown.

teleportTime: 5
# The amount of time to count down before teleporting.

maxPlayers: 4
# The amount of players that you can have at max in your games.

losePerksOnLastStand: true
# Makes players lose all perks when they go into last stand.

pointsGivenOnHelp: 200
# Amount of points to give the player for saving another player.

pointsGivenOnAtomBomb: 600
# Amount of points to give all players when an atom bomb is found.

defaultFriendlyFireMode: false
# The default setting for all games concerning friendly fire.

lastStandThreshold: 10
# The amount of health left before a player is put in last stand.
# Max health is 20, so 10 health = 5 hearts.

endOnLastPlayerLastStand: true
# If the game should end when the last player goes into last stand.

powerupChance: 5
# The chances for the 3 powerups. (atom bomb, barrier fix, weapon fix)

blinkers: true
# Makes areas and barriers blink to reveal position and correctness of placement.
# These are actually fireworks, since the beacon effect is client-side.

addedEffects: true
# Adds extra visual effects to Ablockalypse.

addedSounds: true
# Adds extra audio effects to Ablockalypse.

maxWave: -1
# Sets the highest wave the game can go to before ending.
# If set to -1, the game will go on forever, until all players die in the same level.

barrierPerFixIncrease: 20
# The amount of points gained per fix of the barrier.

barrierCompleteFixIncrease: 100
# The amount of points gained when the barrier is completely fixed.

movingChests: true
# Moves the active chest around, instead of all chests being active at once.

chestBeacons: true
# Adds FIREWORKS (the beacon effect is client-side) above chests to let players see where the active chest is.

levelTransitionTime: 10
# The time, in seconds, before transitioning to the next level after finishing the previous one.

clearNearbyMobs: true
nearbyMobClearingRadius: 32
# If enabled, clears all non-ablockalypse mobs near the player so they don't interfere.

#################################################### MAINTENANCE ####################################################

ENABLE_AUTO_UPDATE: false
# Enables automatic updating for Ablockalypse.

MAX_FATALITY: 100
# The most fatality points that Ablockalypse can take before shutting down. This is used to help
# stop looping errors cause by Ablockalypse.

UPDATE_VERSION: latest
# Which version to download if enabled. The version can be in one of two formats, 
# for example, you can use "1.0.0" to download that version, or you can use "latest" 
# to download the most recent version.

DEBUG: false
# Setting this true will make the console spit out a lot of info at you.
# If there is anything that concerns you, post this as an issue on:
# https://github.com/JamesNorris/Ablockalypse/issues